### PR TITLE
Optimized Italian Language

### PR DESCRIPTION
**Pull request by JohnPetrucci**
Hi, I checked in the screen printer some words are too long, I optimized the text and uploaded new files.

I Wait new zip for flashing.

Thank You!

### CODE REVIEW

**Comment by jojos38** [comment]
Hey I think you made a mistake in the pull request you're trying to pull my Italian branch to my main branch, you should pull your main branch to my Italian branch

**Comment by jojos38** [comment]
[DWIN_SET.zip](https://github.com/jojos38/anycubic-kobra-dark-ui/files/9593895/DWIN_SET.zip)
This zip should have your changes, can you confirm please?

**Comment by JohnPetrucci** [comment]
The Flash is ok, but i have correct one file for HTML error, I have uploaded new file (pages/printing_settings.html)
I'm sorry!
I can Wait new flash file..

**Comment by jojos38** [comment]
[DWIN_SET.zip](https://github.com/jojos38/anycubic-kobra-dark-ui/files/9594359/DWIN_SET.zip)
Here, can you confirm that this works please

**Comment by JohnPetrucci** [comment]
Hi, its work and the Italian Language its OK.

Thank you very much.

**Comment by jojos38** [comment]
No problem

**Pull request closed without merging**
