### PR TITLE
Please Add my traduction an Italian Language 

### PR DESCRIPTION
**Pull request by JohnPetrucci**
Hello, its possible add and compile with Italian Language?, i have edit file an italian language.

Thank You

Paolo

### CODE REVIEW

**Comment by jojos38** [comment]
[DWIN_SET.zip](https://github.com/jojos38/anycubic-kobra-dark-ui/files/9570297/DWIN_SET.zip)
Hey! Thank you, can you try this version and tell me if it works please?

**Comment by JohnPetrucci** [comment]
> [DWIN_SET.zip](https://github.com/jojos38/anycubic-kobra-dark-ui/files/9570297/DWIN_SET.zip) Hey! Thank you, can you try this version and tell me if it works please?

Yes, i flashed files, its all ok, I will check the translation in the next few days.
Thank you

**Comment by JohnPetrucci** [comment]
Hi, I checked in the screen printer some words are too long, I optimized the text and uploaded new files.

I Wait new zip for flashing.

Thank You!

**Comment by jojos38** [comment]
> Author

Hey can you do a pull request please so I can merge

**Comment by JohnPetrucci** [comment]
> > Author
> 
> Hey can you do a pull request please so I can merge

I Add a pull request.

Thanks

**Pull request merged**
